version: '3.8'

networks:
  mysql-db:
    driver: bridge

services:
  desafio-quarkus:
    image: quarkus/desafio-quarkus-jvm:latest
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:mysql://mysql-quarkus:3306/pagamentos?autoReconnect=true
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: 12345678
    networks:
      - mysql-db
    ports:
      - "8080:8080"
    depends_on:
      - mysql-quarkus

  mysql-quarkus:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=pagamentos
    volumes:
      - mysql.quarkus:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mysql-db


volumes:
  mysql.quarkus: